### ISSUE TITLE
Lecture Slides Numbering

### ISSUE THREAD

**Issue by b-beri** [IIITH-Resources/Discrete_Structures#2]
![image](https://user-images.githubusercontent.com/91713017/151650640-98c8ae46-b9ed-42fb-984c-72e19f977d7e.png)
There's some problem with Lecture Slides Numbering. There is no L20. Moreover it seems that there are lesser slides than what sir have covered.

**Comment by adnanqidwai** [comment]
I've added L20 and the introduction lecture, those two are the only ones not here. thanks for reminding
